### PR TITLE
Enable `getrandom/js` feature and test `wasm32-unknown-unknown` in CI

### LINKED ISSUE #36: Add WASM/ WebAssembly support
Hello, @brycx . Your library is awesome. I hope I can use `pasetors` in my web app.

Although there are libraries which already implement PASETO using javascript programming language, unfortunately those aren't running well in browser environment. Those libraries can be used in node.js environment (run javascript inside server). Converting existing library which can be used in browser is not an easy task.

Nowadays, rust can be compiled into WebAssembly (or WASM for short), and then can be used in browser. If you don't mind, could you add WASM support for this library?

### PR DESCRIPTION
**Pull request by brycx**
fixes #36

### CODE REVIEW

**Comment by brycx** [comment]
@achmadk You can try out this branch to see if it covers your use-case.


```toml
[dependencies.pasetors]
git = "https://github.com/brycx/pasetors"
branch = "wasm"
```

**Comment by achmadk** [comment]
Maybe you can implement those additional steps from [this article](https://rustwasm.github.io/book/reference/add-wasm-support-to-crate.html)

Maybe you can also publish generated files of `wasm-pack build` into npm registry. You can read article [here](https://rustwasm.github.io/book/game-of-life/publishing-to-npm.html).

**Comment by brycx** [comment]
> Maybe you can implement those additional steps from this article

All the steps of that article are covered, except for adding `wasm-bindgen` "and `js-sys` and `web-sys`  if you need them". I don't know if the last two are needed in addition to `wasm-bindgen`, but is this the step you are referring to?

> Maybe you can also publish generated files of wasm-pack build into npm registry. You can read article here.

This I won't do. I have never really worked with JS, nor used npm and I have no intentions of starting right now. I'll give it some more thought, perhaps I change my mind in the future. But for now, I don't want to maintain and update two different registries for this crate.

In extension to my lack of experience with JS, if you meant for me to use `wasm-bindgen` and create a  then I'd probably need some help with this due to my lack of knowledge there.

**Comment by achmadk** [comment]
> All the steps of that article are covered, except for adding wasm-bindgen "and js-sys and web-sys if you need them". I don't know if the last two are needed in addition to wasm-bindgen, but is this the step you are referring to?

I think `js-sys` and `web-sys` not need to be added into `Cargo.toml` file.

> In extension to my lack of experience with JS, if you meant for me to use wasm-bindgen then I'd probably need some help with this due to my lack of knowledge there.

Maybe I can help you although I still learning rust programming language for WASM.

**Comment by brycx** [comment]
Thanks! If you end up working on it, feel free to ping me here or on email if you have any questions that I might be able to answer.

I'll merge this pull-request but keep the issue open.

**Pull request merged**
